import { RecommendationCard } from "@/components/recommendation-card";
import type { Recommendation } from "@/lib/types";

/** FR10: ranked list of waiver-wire recommendations. */
export function WaiverList({ recommendations }: { recommendations: Recommendation[] }) {
  if (recommendations.length === 0) {
    return (
      <p className="text-sm text-foreground/60">
        No waiver recommendations yet. They&apos;re generated by the waiver-research
        cron job — run it (or trigger it manually while testing) to populate this.
      </p>
    );
  }

  return (
    <div className="grid gap-3 sm:grid-cols-2">
      {recommendations.map((rec) => (
        <RecommendationCard key={rec.id} recommendation={rec} />
      ))}
    </div>
  );
}
